# sftp example
[narval]
type = sftp
host = narval1.alliancecan.ca
user = $USER

# sftp with ssh key example
[myserver]
type = sftp
host = example.com
user = $USER
port = 22
key_use_agent = true

# s3 example
[ont]
type = s3
provider = AWS
env_auth = false
access_key_id =
secret_access_key =
region = eu-west-1
acl = private
# Match AWS CLI's --no-sign-request (anonymous access)
no_sign_request = true
# (Optional) Use AWS's global endpoint; works well for public buckets
endpoint = s3.amazonaws.com
